<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Oz test</title>

        <?php echo $this->headMeta(); ?>
        <?php echo $this->headScript(); ?>

        <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.css'); ?>
    </head>
    <body>
        <div id="content" style="padding-left:200px;">
            <?php echo $this->layout()->content; ?>
            <div style="clear:both;"></div>
        </div>
    </body>
</html>