<?php if ($this->teams): ?>
    <div class="row">
        <div class="col-md-3">
            <h4>Сводная таблица</h4>
            <table class="table table-striped">
                <tr>
                    <th>Команда</th>
                    <th>Pts</th>
                    <th>P</th>
                    <th>W</th>
                    <th>D</th>
                    <th>L</th>
                    <th>GD</th>
                </tr>
                <?php foreach ($this->team_statistics as $key => $item): ?>
                    <tr>
                        <td><?php echo $this->escape($item['title']); ?></td>
                        <td><?php echo $this->escape($item['pts']); ?></td>
                        <td><?php echo $this->escape($item['p']); ?></td>
                        <td><?php echo $this->escape($item['w']); ?></td>
                        <td><?php echo $this->escape($item['d']); ?></td>
                        <td><?php echo $this->escape($item['l']); ?></td>
                        <td><?php echo $this->escape($item['gd']); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <?php if ($this->round > 0): ?>
            <?php if ($this->week_results): ?>
                <div class="col-md-2">
                    <h4>Результаты матчей</h4>
                    <div>Результаты игр <?php echo $this->escape($this->round); ?>-ой недели</div>
                    <table class="table table-striped">
                        <?php foreach ($this->week_results as $key => $week_result): ?>
                            <tr>
                                <td><?php echo $this->escape($week_result['team_owner_title']); ?></td>
                                <td><?php echo $this->escape($week_result['team_owner_goal_cnt']); ?></td>
                                <td> - </td>
                                <td><?php echo $this->escape($week_result['team_guest_goal_cnt']); ?></td>
                                <td><?php echo $this->escape($week_result['team_guest_title']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>

                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($this->round >= 4 && !$this->is_finish): ?>
            <div class="col-md-2">
                <h4>Предсказание победителя после <?php echo $this->escape($this->round); ?>-ой недели</h4>
                <table class="table table-striped">
                    <?php foreach ($this->team_statistics as $key => $item): ?>
                        <tr>
                            <td><?php echo $this->escape($item['title']); ?></td>
                            <td><?php echo $this->escape($item['forecast']); ?>%</td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>